pip install torch>=1.13.0
pip install torchaudio>=0.13.0
pip install torchvision>=0.14.0
pip install tqdm
pip install gradio
pip install pyyaml
pip install einops
pip install chardet
pip install numpy<=1.23.5
pip install soundfile
pip install librosa==0.9.2
pip install scipy
pip install pandas
pip install torchlibrosa==0.0.9
pip install transformers
pip install progressbar
pip install ftfy
pip install diffusers

